### ISSUE TITLE
Capitalization of letters and hyphens in word hints not accounted for

### ISSUE THREAD

**Issue by ghost** [wlauyeung/Skribblio-Helper#1]

**Comment by wlauyeung** [comment]
Could you elaborate on this or give me an example please?

Edit: I think I know what you mean. I believe the old version of the plugin hyphens were not used as a part of the hint but now it is. Capital letters however, should be working just fine.

**Comment by ghost** [comment]
No, capital letters don't work properly. For example, `timpani` still shows up for `T______`.

**Comment by ghost** [comment]
Now it's even more bugged. I created a private lobby where all ten custom words are Twitter and custom words are used exclusively, but as soon as I used Inspect Element to change the hint for the first letter to `<div class="hint uncover">T</div>` to change it from `_______` to `T______`, only the ~~letters~~ words for the lowercase t show up. Or maybe I clicked Twitter before?

Also, `Band-Aid` now shows up for `________`.

**Comment by wlauyeung** [comment]
> Now it's even more bugged. I created a private lobby where all ten custom words are Twitter and custom words are used exclusively, but as soon as I used Inspect Element to change the hint for the first letter to `<div class="hint uncover">T</div>` to change it from `_______` to `T______`, only the letters for the lowercase t show up. Or maybe I clicked Twitter before?
> 
> Also, `Band-Aid` now shows up for `________`.

Hmm... I tried to reproduce the same behavior but it seems to be working fine on my end. Do you have the old word list cached? Try force refreshing skribbl.io and see if you still have the same issue. If it still persists, try to compare the local word list and the one stored on my [site](https://www.wlay.me/static/json/words.json). If they are the same then send me your word list maybe that made the difference.

**Comment by ghost** [comment]
That's strange. I don't think caching is an issue because I used incognito mode when I played the game, but I used whatever version was the latest on the Chrome Web Store.  Maybe you forgot to push the update to the store? Since you made two updates, I didn't know if the second one updated there yet. Additionally, Chrome only checks for updates every few hours, along with the fact that many updates have to be manually reviewed before they are published. I should've disabled the plugin and downloaded the ZIP from GitHub directly. I will try to force refresh, though.

This is true, but the reason why `Band-Aid` and `Kool-Aid` show for `________` is because they are all eight characters long. It appears as if the extension thinks that's the initial hint for these words, but the initial hint is actually `____-___`. @skribbliohints actually has the hint for every word successfully search that word correctly, with the exception of `AC/DC` (which is actually `_____`, but [they thought it was `__/__`](https://github.com/skribbliohints/skribbliohints.github.io/issues/7#issuecomment-1345406027))

How do I check the local word list on Windows? Also, would you mind removing the unnecessary line 212? ~~The `.replace()` function could be making lowercase words show up for capitalized hints, as it is possible (but I don't think is correct) that `x.replace()` is the same as `x = x.replace()`.~~

**Comment by wlauyeung** [comment]
> That's strange. I don't think caching is an issue because I used incognito mode when I played the game, but I used whatever version was the latest on the Chrome Web Store. Maybe you forgot to push the update to the store? Since you made two updates, I didn't know if the second one updated there yet. Additionally, Chrome only checks for updates every few hours, along with the fact that many updates have to be manually reviewed before they are published. I should've disabled the plugin and downloaded the ZIP from GitHub directly. I will try to force refresh, though.
> 
> This is true, but the reason why `Band-Aid` and `Kool-Aid` show for `________` is because they are all eight characters long. It appears as if the extension thinks that's the initial hint for these words, but the initial hint is actually `____-___`. @skribbliohints actually has the hint for every word successfully search that word correctly, with the exception of `AC/DC` (which is actually `_____`, but [they thought it was `__/__`](https://github.com/skribbliohints/skribbliohints.github.io/issues/7#issuecomment-1345406027))
> 
> How do I check the local word list on Windows? Also, would you mind removing the unnecessary line 212? ~The `.replace()` function could be making lowercase words show up for capitalized hints, as it is possible (but I don't think is correct) that `x.replace()` is the same as `x = x.replace()`.~

The hyphen issue should be resolved. 

For the other issue, I'd recommend sticking with the zip instead of relying on the official extension. If it is still glitching out with the zipped version let me know. For the local storage I usually just do a quick `console.log(this.#words)`.
